### ISSUE TITLE
Required property visual clue is missing on input fields

### ISSUE THREAD

**Issue by peterblazejewicz** [Microsoft/YamUI#248]
Hi,

It seems that components that derives from base text field do not have a visual clue rendered when the component has a `required` property set to true:
```css
/* Hide the asterisk that comes with required=true */
.y-base-text-field .ms-Label::after,
.y-base-text-field .ms-TextField-fieldGroup::after {
  display: none;
}
```
The relevant section from Fabric:
https://developer.microsoft.com/en-us/fabric#/components/textfield

Thanks!
